### PR TITLE
gitup.conf, gitup.conf.sample: releng/13.2, stable/14

### PR DESCRIPTION
**Pull request by grahamperrin**
`releng/11.4` is end of life, so update the `release` section of configuration files.

Whilst here: update the `stable` section.

### CODE REVIEW

**Comment by grahamperrin** [comment]
How is `/usr/local/etc/gitup.conf.sample` created?

<details>
<summary>My gitup.conf.sample</summary>

```text
% pkg iinfo gitup
gitup-0.98.8
% cat /usr/local/etc/gitup.conf.sample
# $FreeBSD$
#
# Default configuration options for gitup.conf.
{
        "defaults" : {
                "host"           : "git.freebsd.org",
                "port"           : 443,
#               "proxy_host"     : "",
#               "proxy_port"     : 0,
#               "proxy_username" : "",
#               "proxy_password" : "",
#               "source_address" : "",
                "low_memory"     : false,
                "display_depth"  : 0,
                "verbosity"      : 1,
                "work_directory" : "/var/db/gitup",
        },

        "ports" : {
                "repository_path"  : "/ports.git",
                "branch"           : "main",
                "target_directory" : "/usr/ports",
                "ignores"          : [],
        },

        "quarterly" : {
                "repository_path"  : "/ports.git",
                "branch"           : "quarterly",
                "target_directory" : "/usr/ports",
                "ignores"          : [],
        },

        "release" : {
                "repository_path"  : "/src.git",
                "branch"           : "releng/11.4",
                "target_directory" : "/usr/src",
                "ignores"          : [
                        "sys/[^\/]+/conf",
                ],
        },

        "stable" : {
                "repository_path"  : "/src.git",
                "branch"           : "stable/12",
                "target_directory" : "/usr/src",
                "ignores"          : [
                        "sys/[^\/]+/conf",
                ],
        },

        "current" : {
                "repository_path"  : "/src.git",
                "branch"           : "main",
                "target_directory" : "/usr/src",
                "ignores"          : [
                        "sys/[^\/]+/conf",
                ],
        }
}
% 
```

</details>

**Comment by MartinVonReichenberg** [comment]
> How is `/usr/local/etc/gitup.conf.sample` created?
> 
> I see <https://github.com/freebsd/freebsd-ports/blob/main/net/gitup/pkg-post-install>, however I'm confused because my local _sample_ file (below) is so different from the `gitup.conf` in this repo. 
> 
> <details>
> <summary>My gitup.conf.sample</summary>
> 
> ```text
> % pkg iinfo gitup
> gitup-0.98.8
> % cat /usr/local/etc/gitup.conf.sample
> # $FreeBSD$
> #
> # Default configuration options for gitup.conf.
> {
>         "defaults" : {
>                 "host"           : "git.freebsd.org",
>                 "port"           : 443,
> #               "proxy_host"     : "",
> #               "proxy_port"     : 0,
> #               "proxy_username" : "",
> #               "proxy_password" : "",
> #               "source_address" : "",
>                 "low_memory"     : false,
>                 "display_depth"  : 0,
>                 "verbosity"      : 1,
>                 "work_directory" : "/var/db/gitup",
>         },
> 
>         "ports" : {
>                 "repository_path"  : "/ports.git",
>                 "branch"           : "main",
>                 "target_directory" : "/usr/ports",
>                 "ignores"          : [],
>         },
> 
>         "quarterly" : {
>                 "repository_path"  : "/ports.git",
>                 "branch"           : "quarterly",
>                 "target_directory" : "/usr/ports",
>                 "ignores"          : [],
>         },
> 
>         "release" : {
>                 "repository_path"  : "/src.git",
>                 "branch"           : "releng/11.4",
>                 "target_directory" : "/usr/src",
>                 "ignores"          : [
>                         "sys/[^\/]+/conf",
>                 ],
>         },
> 
>         "stable" : {
>                 "repository_path"  : "/src.git",
>                 "branch"           : "stable/12",
>                 "target_directory" : "/usr/src",
>                 "ignores"          : [
>                         "sys/[^\/]+/conf",
>                 ],
>         },
> 
>         "current" : {
>                 "repository_path"  : "/src.git",
>                 "branch"           : "main",
>                 "target_directory" : "/usr/src",
>                 "ignores"          : [
>                         "sys/[^\/]+/conf",
>                 ],
>         }
> }
> % 
> ```
> 
> </details>



The GitHub repository is not the primary place for making changes to internal FreeBSD software.
FreeBSD developers use this _cgit_ repository for committing changes to the software code:
[CGIT](https://cgit.freebsd.org/ports/tree/net/gitup)
The file you are looking for is here: [GitUP](https://github.com/johnmehr/gitup/blob/main/gitup.conf)
.

**Comment by grahamperrin** [comment]
> The file you are looking for is here: [GitUP](https://github.com/johnmehr/gitup/blob/main/gitup.conf?rgh-link-date=2023-09-24T10%3A39%3A11Z)

No, `gitup.conf` was found before I made this pull request. Please see the _Files changed_ tab.

**Comment by johnmehr** [comment]
Thank you!

**Comment by MartinVonReichenberg** [comment]
> > The file you are looking for is here: [GitUP](https://github.com/johnmehr/gitup/blob/main/gitup.conf?rgh-link-date=2023-09-24T10%3A39%3A11Z)
> 
> No, `gitup.conf` was found before I made this pull request. Please see the _Files changed_ tab.

But the initial question was: _How is /usr/local/etc/gitup.conf.sample created?_

The answer is simple.

It is made of the already mentioned `gitup.conf` file by telling the package builder (MAKEFILE) to create/make/install something out of something else (basically only in the terms of names) - Like in Alchemy:
```
34   ${INSTALL_DATA} ${WRKSRC}/gitup.conf \
35   		${STAGEDIR}${PREFIX}/etc/gitup.conf.sample
```
Mentioned in: 
https://cgit.freebsd.org/ports/tree/net/gitup/Makefile
https://cgit.freebsd.org/ports/tree/net/gitup/files/pkg-message.in


_So was I referring to that . . ._

**Comment by grahamperrin** [comment]
Ah, thank you, @MartinVonReichenberg, yes, it was direction to (permalink) https://github.com/freebsd/freebsd-ports/blob/83058c529515ca422e41893e158e321f7b4a3bce/net/gitup/Makefile#L34-L35 that I needed. 

----

I was partly thrown by your mention of internal FreeBSD software. 

I did, in May 2023, suggest inclusion of Gitup (and GoT) in base, for FreeBSD 14.0-RELEASE, however that was a private discussion (the `developers@` list), whilst I was a committer.

**Pull request merged**
